#!/usr/bin/env bash

# A helper script for building Python on Linux from source and installing it
# to a self-contained location such as /opt/python/3.4.5 that can be
# easily uninstalled by just deleting the directory.
#
# The complete steps are:
#
# - make a temporary directory to build in
# - download the source tarball and associated GPG signature file
# - verify the signature using GPG, aborting if gpg --verify fails
#   (see https://www.python.org/downloads/ for importing necessary pub keys)
# - unpack the tarball
# - configure the build using secure options and generic optimization (by default)
# - compile using as many processes as there are processors on this machine;
# - if RUNTESTS=1, then we run the Python test suite and report the results
# - if NOINSTALL=1, then we stop here and don't install or remove the build dir
# - install the built Python using 'altinstall (which doesn't make symlinks
#   of python3 -> python3.5, for example) if ALTINSTALL=1 or using
#   the normal 'install' target otherwise (which also creates symlinks
#   from versions like python2 or python3 to the actual exe such as python2.7
#   or python3.5).
# - install Pip if needed, forcing upgrade to latest version if PIPUPGRADE=1
# - install IPython if needed, unless NOIPYTHON is set to 1, upgrading
#   to existing version if IPYTHONUPGRADE=1.
# - save log files of preceeding in a .build subdirectory of the install dir
# - remove the build directory (containing all temp files) unless NOCLEANUP=1
#
# See the usage info for all options that are configurable
# by environment variables (e.g., install-python --help).

# Source utils if running as a script (not source ourselves). This is
# at the top so that variables and functions defined in this module override
# any defined in the util script that have the same name.
if [[ "${BASH_SOURCE:-$_}" = "${0}" ]]
then
    # shellcheck source=install-util.sh
    source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/install-util.sh" || {
        >&2 echo "ERROR: couldn't source install-util.sh script from installers directory"
        exit 1
    }
fi

# The container directory for different Python versions that are installed
# when no target directory is specificed.
PYBASE="${PYBASE:-/opt/python}"

# The package extension of the Python package to download; 'tgz'
# seems to exist for all versions, so that's the default.
EXT="${EXT:-tgz}"

# Package template for Python package (e.g., Python-3.6.1.tgz),
# used by URL template below and the 'url' helper function.
PACKAGE="Python-\${version}.${EXT}"

# URL template for URL to download the Python package from;
# the 'url' function below will interpolate the version that
# is passed as the first arg to yield the actual URL, and
# will take care of extracting a 'base_version' from the 'version'
# for versions like '3.7.0b1', where the base_version in the
# URL before the PACKAGE would be '3.7.0', but the full
# '3.7.0b1' is in the PACKAGE part.
URL="https://www.python.org/ftp/python/\${base_version}/${PACKAGE}"

# gcc -mtune value, which determines how instructions are optimized;
# we use generic by default in order to be more useful for building
# and running on different machines.
MTUNE="${MTUNE:-generic}"

# gcc -march value, if provided; if not provided, we don't include
# -march, and rely on gcc to use its default.
MARCH="${MARCH:-}"

# If set to 1, then we leave the temporary directory that contains
# the Python download, build directory, and compilation artifcacts
# and log files.
NOCLEAN="${NOCLEAN:-0}"

# If set to 1, then we halt after compilation and don't install
# or cleanup.
NOINSTALL="${NOINSTALL:-0}"

# If set to 1, then don't install IPython.
NOIPYTHON="${NOIPYTHON:-0}"

# If set to 1, then if Pip is installed already, try to upgrade
# to the latest version.
PIPUPGRADE="${PIPUPGRADE:-0}"

# If set to 1, then if IPython is already installed, try to
# upgrade to the latest version.
IPYTHONUPGRADE="${IPYTHONUPGRADE:-0}"

## The ENABLE* flags expose the most commonly used configure options.  ##

# If set to 1 (default), create ipv6 aware python ('--enable-ipv6'),
# and if set to 0, ipv6 will not be supported ('--disable-ipv6').
ENABLEIPV6="${ENABLEIPV6:-1}"

# If set to 1 (default is 0), then '--enable-optimizations' is used for
# Python versions that support it. The install takes much longer, but
# the performance improvements are significant.
ENABLEOPTIMIZATIONS="${ENABLEOPTIMIZATIONS:-0}"

# If set to 1 (default is 0), try to use the system expat
# ('--with-system-expat' option).
ENABLESYSTEMEXPAT="${ENABLESYSTEMEXPAT:-0}"

# If set to 1 (default is 0), try to use the system libffi
# ('--with-system-libffi' option).
ENABLESYSTEMFFI="${ENABLESYSTEMFFI:-0}"

# If set to 1 (default), then use the option to enable loadable extensions
# in the sqlite3 module ('--enable-loadable-sqlite-extensions' option).
ENABLESQLITEEXTENSIONS="${ENABLESQLITEEXTENSIONS:-1}"

# If set to 1 (default is 0), then use make a pydebug build, which is
# useful for running the Python tests and debugging.
ENABLEPYDEBUG="${ENABLEPYDEBUG:-0}"

# If set to 1 (default is 0), then the Python test suite will be run
# after compiling and before installing.
RUNTESTS="${RUNTESTS:-0}"

# If set to 1 (default), then if we run tests and there is a failure,
# we still continue with remaining tasks. The default is 1, because
# it's not that uncommon that at least 1 test is failing due to
# some dependency problem or some other issue that doesn't necessarily
# indicate something went wrong with the build.
# If set to '0', then any non-zero exit status when running tests
# causes us to abort and leave the build directory around for inspection.
TESTFAILOK="${TESTFAILOK:-1}"

# If set to 1 (default is 0), run 'make altinstall' to install
# instead of 'make install', which just installs versioned binaries
# such as 'python3.6' and not the 'python3 -> python3.6' symlinks
# that 'make install' creates.
ALTINSTALL="${ALTINSTALL:-0}"

# If set to 1 (default is 0), then if there is already a Python installed
# at the target install directory, we overwrite it; otherwise, we
# just notify that it already exists and skip the Python
# install step (but Pip and IPython proceed as normally).
CLOBBER="${CLOBBER:-0}"

usage() {
    echo "usage: ${1:-install-python} VERSION [INSTALLDIR]"
    echo
    echo "Parameters:"
    echo " - VERSION: full Python version, such as 3.6.1"
    echo " - INSTALLDIR: optional directory to install to [default is to use"
    echo "       the full version number as the directory name inside"
    echo "       \${PYBASE}, which defaults to /opt/python]"
    echo
    echo "Environment Variables:"
    echo " - MTUNE: optimization target passed as -mtune to gcc [default is generic]"
    echo " - MARCH: machine type to generate instructions for, passed as"
    echo "       -march to gcc [default is none, to use gcc default]"
    echo " - EXT: file extension for package to download [default is tgz]"
    echo " - RUNTESTS: if set to 1 (default is 0), then the Python test suite"
    echo "       will be run and the results printed; this happens after the"
    echo "       build stage and before installation; to run the tests, "
    echo "       you probably want to use all of"
    echo "       NOCLEAN=1 ENABLEPYDEBUG=1 NOINSTALL=1 RUNTESTS=1"
    echo "       See also the TESTFAILOK variable for how to react to failure."
    echo " - NOCLEAN: if set to 1, the temporary directory will not be"
    echo "       removed [default is to remove it only on success]"
    echo " - NOINSTALL: if set to 1, then don't install Python, just compile it"
    echo "       and leave the compiled artifacts in the build directory"
    echo " - NOIPYTHON: if set to 1, then IPython won't be installed"
    echo " - PYBASE: a base directory [defaults to /opt/python] for versioned"
    echo "       subdirectories [such as /opt/python/3.6.1] to use as the"
    echo "        installation target directory when no INSTALLDIR arg is given"
    echo " - ENABLESQLITEEXTENSIONS: if set to 1 (default), then use the"
    echo "       --enable-loadable-sqlite-extensions configure option"
    echo "       or apply the manual patch that was required before that"
    echo "       configure option was added"
    echo " - ENABLEIPV6: if set to 1 (default), then use the --enable-ipv6"
    echo "       configure option, and if 0, use --disable-ipv6."
    echo " - ENABLEOPTIMIZATIONS: if set to 1 (defualt is 0), then use"
    echo "       the --enable-optimizations configure option for newer"
    echo "       Python versions that support it."
    echo " - ENABLESYSTEMEXPAT: if set to 1 (default is 0), then use"
    echo "       the --with-system-expat configure option if supported."
    echo " - ENABLESYSTEMFFI: if set to 1 (default is 0), then use"
    echo "       the --with-system-ffi configure option if supported."
    echo " - ENABLEPYDEBUG: if set to 1 (default is 0), then use"
    echo "       the --with-pydebug configure option, which is useful"
    echo "       for testing and debugging"
    echo " - TESTFAILOK: if set to 0 (default is 1), then abort without "
    echo "       installing anything if the test suite returns a non-zero"
    echo "       exit status indicating at least 1 test failed."
    echo " - CLOBBER: if set to 1 (default is 0), then any existing Python"
    echo "       at the install location will be ovewritten; otherwise we"
    echo "       skip the install step and note that it was skipped"
    echo "       (but the Pip and IPython steps still happen)"
    echo " - WITH_OPENSSL: if set to a non-empty string value, it should "
    echo "       be the base path of a compatible OpenSSL installation, "
    echo "       such as /opt/openssl/1.0.2n if you compiled and installed "
    echo "       openssl with the --prefix=/opt/openssl/1.0.2n and "
    echo "       --openssldir=/opt/openssl/1.0.2n/openssl options."
}

# Interpolate 1st param as version into PACKAGE template defined above.
package() {
    local -r version=${1:?version parameter is required}
    eval "echo \"${PACKAGE}\""
}

# Echo first two parts of version given as 1st param (e.g., 3.6 for 3.6.1p0).
major_version() {
    local version=${1:?version parameter is required}
    [[ -n "${version}" ]] ||
        err "invalid version: ${version}" ||
        return
    local result
    result=$(grep -E -o '^[0-9]+\.[0-9]+' 2>/dev/null <<< "${version}") ||
        err "couldn't extract X.Y version from: ${version}" ||
        return
    echo -n "${result}"
}

# Echo path to the unpacked Python source directory given the build
# directory and the version as the first and second params, respectively.
src_dir() {
    local -r build_dir=${1:?build_dir parameter is required}
    local -r version=${2:?version parameter is required}
    local _dir
    _dir="${build_dir}/$(basename "$(package "${version}")" ".${EXT}")" ||
        return
    echo -n "${_dir}"
}

# Echo the URL of the Python source package given version as first param.
url() {
    local -r version=${1:?version parameter is required}

    # The Python download URL uses the full version, such as '3.7.0b1'
    # in PACKAGE part of the URL (Python-3.7.0b1.tar.gz), but only
    # the '3.7.0' part in the parent directory that contains the file
    # (interpreting the URL structure as if it mapped to the filesystem,
    # which it probably does in this case).
    # shellcheck disable=SC2034
    local -r base_version=$(expr match "${version}" "\([0-9]*\.[0-9]*\.[0-9]*\)")

    eval "echo \"${URL}\""
}

# Download Python source package and signature.
# The first param should be the directory to download into, which must
# already exist, and the second param should be the version (e.g., 3.6.1).
download_package_and_signature() {
    local -r build_dir=${1:?build_dir parameter is required}
    local -r version=${2:?version parameter is required}

    verify_dir "${build_dir}" || return

    local packageurl
    packageurl=$(url "${version}") || return

    echo -n " - downloading from ${packageurl}"
    download_and_verify "${packageurl}" "${packageurl}.asc" "${build_dir}"
}

# Run the configure step given params for the build directory in which the
# source has already been unpacked, the Python version, and the target
# installation directory, respectively.
configure() {
    local -r build_dir=${1:?build_dir parameter is required}
    local -r version=${2:?version parameter is required}
    local -r destdir=${3:?destdir parameter is required}

    local packagedir
    packagedir=$(src_dir "${build_dir}" "${version}") || return

    echo -n " - configuring"
    change_dir "${packagedir}" || return

    local -a copts

    # Some python3 versions have with-wide-unicode, which is the equivalent
    # of --enable-unicode=ucs4 under python2
    if has_configure_opt --with-wide-unicode
    then
        copts+=(--with-wide-unicode)
    else
        if has_configure_opt --enable-unicode
        then
            copts+=("--enable-unicode=ucs4")
        fi
    fi

    # Python 3.2 and higher have this option, but the sqlite3 on macs
    # does not support it, so don't enable on mac for any version
    if [[ $OSTYPE != darwin* ]] && [[ "${ENABLESQLITEEXTENSIONS}" = "1" ]]
    then
        if has_configure_opt --enable-loadable-sqlite-extensions
        then
            copts+=(--enable-loadable-sqlite-extensions)
        fi
    fi

    # Same dbm order as debian (but with ndbm added as well as the last option):
    if has_configure_opt --with-dbmliborder
    then
        copts+=("--with-dbmliborder=bdb:gdbm:ndbm")
    fi

    # We install Pip manually below so that we can use get-pip.py and
    # thus install identically across all Python versions, rather than
    # relying on '--ensure-pip' for those versions that support it
    # and get-pip.py for those that don't.
    if has_configure_opt --with-ensurepip
    then
        copts+=(--without-ensurepip)
    fi

    if has_configure_opt --enable-ipv6
    then
        case "${ENABLEIPV6}" in
            1) copts+=(--enable-ipv6);;
            0) copts+=(--disable-ipv6);;
            *) echo -n " - ignoring invalid ENABLEIPV6=${ENABLEIPV6} setting";;
        esac
    fi

    if has_configure_opt '--with-hash-algorithm=.*\bsiphash24\b'
    then
        copts+=("--with-hash-algorithm=siphash24")
    fi

    if [[ ${ENABLESYSTEMEXPAT} = 1 ]] && has_configure_opt --with-system-expat
    then
        copts+=(--with-system-expat)
    fi

    if [[ ${ENABLESYSTEMFFI} = 1 ]] && has_configure_opt --with-system-ffi
    then
        copts+=(--with-system-ffi)
    fi

    if [[ ${ENABLEOPTIMIZATIONS} = 1 ]] && has_configure_opt --enable-optimizations
    then
        copts+=(--enable-optimizations)
    fi

    if [[ ${ENABLEPYDEBUG} = 1 ]]
    then
        copts+=(--with-pydebug)
    fi

    if [[ -n ${WITH_OPENSSL} ]]
    then
        copts+=(--with-openssl=${WITH_OPENSSL})
    fi

    set +u

    # --enable-shared is omitted because this isn't intended to be a system
    # python that is available for embedding by other apps, and there seems
    # to be a small performance advantage to not enabling it and fewer
    # complications with finding existing libpython unintentionally.

    # shellcheck disable=SC2046,SC2068
    run_clean ./configure \
        --prefix="${destdir}" \
        ${copts[@]} \
        LDFLAGS=-Wl,-z,relro,-z,now,-rpath="${destdir}/lib" \
        > "${build_dir}"/configure.log 2>&1
    stage_complete configure "${build_dir}" $?
}

# Run the compile step given params for the build directory in which the
# source has already been unpacked and configured, the Python version, and
# the target installation directory, respectively.
compile() {
    local -r build_dir=${1:?build_dir parameter is required}
    local -r version=${2:?version parameter is required}
    local -r destdir=${3:?destdir parameter is required}
    local mversion
    mversion=$(major_version "${version}") || return

    # verify no spaces in the vars we use that could affect splitting
    [[ ${destdir} != *" "* ]] || {
        err "invalid dest dir: ${destdir}"
        return 1
    }
    [[ ${MARCH} != *" "* ]] || {
        err "invalid dest dir: ${MARCH}"
        return 1
    }
    [[ ${MTUNE} != *" "* ]] || {
        err "invalid dest dir: ${MTUNE}"
        return
    }

    # Only set MAKEFLAGS if not already in environment, since we want to
    # honor MAKEFLAGS="" if provided by not using any flags.
    local makeflags
    if ! command env | grep -E '^MAKEFLAGS=' >/dev/null 2>&1
    then
        # Compile in parallel (no limit):
        makeflags=-j
    fi

    local cflags=(
        "-fPIC"                      # position-independent code
        "-fstack-protector-strong"   # buffer overflow protection (GCC 4.9+)
        "--param=ssp-buffer-size=4"  # for funcs with buffers >= 4-bytes
        "-Wp,-D_FORTIFY_SOURCE=2"    # more buffer overflow protection
        "-fexceptions"               # enable exception handling
        "-Wstrict-prototypes"        # warn if arg types not specified
        "-Wformat"                   # printf/scanf... warnings
        "-Wformat-security"          # and security concerns for same
        "-mtune=${MTUNE}"            # optimization target
        "-DNDEBUG"                   # disable build-time C asserts (required)
        "-I${destdir}/include/python${mversion}:/usr/local/include:/usr/include"
    )
    [[ -n "${MARCH}" ]] && cflags+=("-march=${MARCH}")

    echo -n " - compiling"
    change_dir "$(src_dir "${build_dir}" "${version}")" || return

    local make_command=()
    local -r ccache="$(which ccache 2>/dev/null)"
    [[ -s "${ccache}" ]] && make_command+=(ccache)
    make_command+=(make)
    run_clean "${make_command[@]}" CFLAGS="$(join_by ' ' "${cflags[@]}")" "${makeflags[@]}" > "${build_dir}"/compile.log 2>&1
    stage_complete compile "${build_dir}" $?
}

# Run the Python test suite for the Python version given as 2nd param
# using the already compiled Python source that used the base directory
# given as the 1st param.
run_tests() {
    local -r build_dir=${1:?build_dir parameter is required}
    local -r version=${2:?version parameter is required}

    change_dir "$(src_dir "${build_dir}" "${version}")" || return
    local libdir
    libdir="$(command ls -d -1 build/lib*)" || return

    local -r testclass=$(if [[ "${version:0:1}" = "2" ]]; then echo -n test.regrtest; else echo -n test; fi)
    run_clean LD_LIBRARY_PATH="${libdir}" ./python -m "${testclass}" > "${build_dir}"/test.log 2>&1 || {
        local -r rc=$?
        echo " - failed with code ${rc}:"
        sed -n -E '/[:digit:]* tests OK\./,$p' < "${build_dir}"/test.log
        echo "See ${build_dir}/test.log for more info"
        return $rc
    }
}

# Install the already compiled Python that was unpacked, configured,
# and compiled in the build directory given as the first param, for
# the specific Python version given as the second param.
install() {
    local -r build_dir=${1:?build_dir parameter is required}
    local -r version=${2:?version parameter is required}

    local -r installtarget=$(if [[ "${ALTINSTALL}" = "1" ]]; then echo -n altinstall; else echo -n install; fi;)
    echo -n " - installing"
    change_dir "$(src_dir "${build_dir}" "${version}")" || return
    run_clean make "${installtarget}" > "${build_dir}"/install.log 2>&1
    stage_complete install "${build_dir}" $?
}

# Install Pip if it is not yet installed into the Python directory given
# as the second param by downloading get-pip.py in the build directory
# given as the first param and using the target Python to run get-pip.py.
# The third param should be the version.
install_pip() {
    local -r build_dir=${1:?build_dir parameter is required}
    local -r installdir=${2:?installdir parameter is required}
    local -r version=${3:?version parameter is required}

    local mversion
    mversion=$(major_version "${version}") || return
    local -r bindir="${installdir}/bin"
    local -r pip_bin="${bindir}/pip${mversion}"

    echo -n " - installing Pip"
    # exit status of last command in each path through conditional
    # is used as the status for this stage as a whole
    if [[ ! -f "${pip_bin}" ]]
    then
        change_dir "${build_dir}" || return
        download "${build_dir}" 'https://bootstrap.pypa.io/get-pip.py' ||
            return
        "${bindir}/python${mversion}" get-pip.py > "${build_dir}"/install_pip.log 2>&1
    else
        if [[ "${PIPUPGRADE}" = "1" ]]
        then
            echo -n " - upgrading existing"
            run_clean "${bindir}/pip${mversion}" install -q -U pip > "${build_dir}"/install_pip.log 2>&1
        else
            echo -n " - already installed"
        fi
    fi
    stage_complete install_pip "${build_dir}" "$?"
}

install_ipython() {
    local -r build_dir=${1:?build_dir parameter is required}
    local -r installdir=${2:?installdir parameter is required}
    local -r version=${3:?version parameter is required}

    [[ -d "${installdir}" ]] ||
        err "installdir does not exist: ${installdir}" ||
        return

    local mversion
    mversion=$(major_version "${version}") ||
        err "invalid version: ${version}" ||
        return

    echo -n " - installing IPython"
    # exit status of last command in each path through conditional
    # is used as the status for this stage as a whole
    if [[ "${NOIPYTHON}" = "1" ]]
    then
        echo -n " - skipping due to NOIPYTHON=1"
    else
        local -r pip_bin="${installdir}/bin/pip${mversion}"
        local -r ipython_log="${build_dir}"/install_ipython.log
        if [[ ! -f "${installdir}/bin/ipython" ]]
        then
            run_clean "${pip_bin}" -q install ipython > "${ipython_log}" 2>&1
        else
            if [[ "${IPYTHONUPGRADE}" = "1" ]]
            then
                echo -n ' - upgrading existing'
                run_clean "${pip_bin}" -q install -U ipython > "${ipython_log}" 2>&1
            else
                echo -n " - already installed"
            fi
        fi
    fi
    stage_complete install_ipython "${build_dir}" $?
}

# Install from source a Python version given as the first param to the
# target directory given as the second parameter.
install_python_main() {
    local -r version=${1:?version parameter is required}
    local -r installdir="${2:-${PYBASE}/${version}}"

    # this variable is used by the exit trap and determines whether we
    # 'rm -rf' the build directory. If NOCLEAN is 1, then we never cleanup,
    # but if it's any other value, then we'll try to do the "right thing"
    # by deleting if everything goes according to plan and we actually
    # install something into the target directory.
    local cleanup
    cleanup=$(if [[ "${NOCLEAN:0}" = "1" ]]; then echo -n 0; else echo -n 1; fi)

    # check for -h or --help anywhere in args, and show usage and return if found
    local arg
    for arg in "$@"; do
        case "${arg}" in
            -h|--help)
                usage "$(basename "$0")"
                return 0
        esac
    done

    echo " - install dir: ${installdir}"

    local mversion
    mversion=$(major_version "${version}") || return

    local parentdir
    parentdir=$(cd "$(dirname "${installdir}")" && pwd -P)

    if [[ ! -d "${installdir}" ]]
    then
        # install dir doesn't exist, so verify that we can write to parent
        # dir and fail before downloading anything if not
        if [[ ! -w "${parentdir}" ]]
        then
            err "directory ${installdir} does not exist or ${parentdir} is not writable"
            return
        fi
    fi

    # use mktemp to create a build directory with a friendly name, under
    # the user's TMPDIR location; we set a strict umask for creating
    # the directory, but only change umask this once to keep
    # the temp directory private (but not the contents after they're
    # moved elsewhere outside that directory).
    local build_dir
    build_dir="$(umask 077 && mktemp -d -t install-python-"$(tr . - <<< "${version}")"-XXXXXX)" || {
        local -r rc=$?
        echo "error ${rc} creating build_dir using mktemp -d"
        echo "Check \$TMPDIR and verify that it is set to a suitable directory"
        return $rc
    }

    # Set up exit trap. We can't use a function without making more variables
    # be globals, so we rely instead on single quoting to not evaluate the
    # trap commands until the trap fires for some non-zero status code.
    # The handler deletes the build_dir we just created if and only if
    # "${cleanup}" is set to '1', and then it exits with the original
    # failed status.
    # shell-check disable=SC2064,SC2154
    trap 'local -r rc=$?; if [[ "${cleanup}" = "1" ]]; then command rm -rf "${build_dir}"; fi; exit $rc' ERR

    local -r targetpython="${installdir}/bin/python${mversion}"

    # Build and do other pre-install steps in the following cases:
    #  1. the target python binary doesn't exist
    #  2. NOINSTALL=1, in which case we don't care whether the target python
    #     binary exists, as we're probably going to run the test suite
    #     or experiment with configuration/compilation options.
    #  3. CLOBBER=1, in which case we'll overwrite any existing installation
    #     at the target location
    if [[ "${CLOBBER}" = "1" || "${NOINSTALL}" = "1" || ! -f "${targetpython}" ]]
    then
        echo " - build dir: ${build_dir}"
        # most of the commands below follow the same general pattern of
        # running the command and on failure, ensuring the build directory
        # and any built artifacts are kept around (cleanup=0) for
        # manual inspection and possible additional attempts to
        # configure/compile/install/etc. with different options,
        # and then the original non-zero status is returned to exit
        # this function after 'cleanup=0' has been set.
        download_package_and_signature "${build_dir}" "${version}" || {
            local -r rc=$?
            cleanup=0
            return $rc
        }
        unpack "${build_dir}"/"$(package "${version}")" || {
            local -r rc=$?
            cleanup=0
            return $rc
        }
        echo
        configure "${build_dir}" "${version}" "${installdir}" || {
            local -r rc=$?
            cleanup=0
            return $rc
        }
        echo
        compile "${build_dir}" "${version}" "${installdir}" || {
            local -r rc=$?
            cleanup=0
            return $rc
        }
        echo
        if [[ ${RUNTESTS} = 1 ]]
        then
            run_tests "${build_dir}" "${version}" || {
                local -r rc=$?
                case "${TESTFAILOK}" in
                    0) cleanup=0; return $rc;;
                    1) ;;
                    *) echo "ignoring TESTFAILOK with invalid value: ${TESTFAILOK}";;
                esac
            }
        fi
        if [[ ${NOINSTALL} = 1 ]]
        then
            # don't clean up if not installing unless they explicitly asked
            # for it by setting NOCLEAN to 1 (default is 0)
            if [[ ${NOCLEAN} != 1 ]]
            then
                cleanup=0
            fi
            return 0
        fi
        install "${build_dir}" "${version}" || {
            local -r rc=$?
            echo
            cleanup=0  # don't clean up if install failed
            return $rc
        }
        echo

        # add 'default' symlink if installing to standard BASE/VERSION location
        if [[ "${installdir}" = "${PYBASE}/${version}"  ]]
        then
            add_default_symlink "${PYBASE}" "${version}"
        fi
    else
        echo " - Python already exists: ${targetpython}"
    fi

    install_pip "${build_dir}" "${installdir}" "${version}" || {
        local -r rc=$?
        echo
        cleanup=0  # don't clean up, so user can debug the failure
        return $rc
    }
    echo

    install_ipython "${build_dir}" "${installdir}" "${version}" || {
        local -r rc=$?
        echo
        cleanup=0  # don't clean up
        return $rc
    }
    echo

    # preserve all the logs under a .build directory inside the install dir
    if [[ -n "$(find "${build_dir}" -maxdepth 1 -name '*.log' -print -quit)" ]]
    then
        echo -n " - saving logs to ${installdir}/.build"
        mkdir -p "${installdir}/.build" ||
            err " - couldn't create .build directory" ||
            return
        # copy with preserve if it doesn't exist at target or the
        # the source file is newer than the file in the .build dir
        cp -p -u "${build_dir}"/*.log "${installdir}/.build/"
        echo
    fi
}

# run only if not sourced, so this script can be sourced for interactive use
if [[ "${BASH_SOURCE:-$_}" = "${0}" ]]
then
    install_python_main "$@"
fi
