#!/usr/bin/env bash

set -o pipefail

REPOS="${REPOS:-$HOME/repos}"
NGHTTP2_BASE="${NGHTTP2_BASE:-/opt/nghttp2}"

# Run a build command with minimal environment, limited to
# LANG, LANGUAGE, and a minimal PATH containing just /usr/bin and /bin,
# and echoing the exact command to be executed before executing it.
run_clean() {
    local -r language="${LANGUAGE:-en_US}"
    local -r lang="${LANG:-${language}.UTF-8}"

    echo env -i PATH=/usr/bin:/bin LANGUAGE="${language}" LANG="${lang}" "$@"
    env -i PATH=/usr/bin:/bin LANGUAGE="${language}" LANG="${lang}" "$@"
}

get_python_version() {
    local -r full_version=$(run_clean python --version 2>&1 | tail -n 1 | grep -E -o '(\.|[[:digit:]])+' | tr -d '\s')
    echo -n "${full_version}" | command grep -E -o '[[:digit:]]+\.[[:digit:]]+'
}

install_nghttp2_main() {
    local -r version="${1:?version param is required}"
    local -r install_dir="${NGHTTP2_BASE}/${version}"

    local -r python_version=$(get_python_version) || {
        local -r rc=$?
        >&2 echo "ERROR: couldn't determine python version"
        return $rc
    }
    local -r pythonpath="${install_dir}/lib/python${python_version}/site-packages"

    cd "${REPOS}/nghttp2" || {
        local -r rc=$?
        >&2 echo "ERROR: Git repo not found at expected location: ${REPOS}/nghttp2"
        return $rc
    }
    command git checkout "v${version}" || {
        local -r rc=$?
        >&2 echo "ERROR: error checking out git version v${version}"
        return $rc
    }

    command mkdir -p "${install_dir}" || return
    command git submodule update --init || return
    run_clean autoreconf -i || return
    run_clean automake || return
    run_clean autoconf || return
    run_clean ./configure \
        PYTHONPATH="${pythonpath}" \
        --prefix="${install_dir}" || \
        return
    local make_command=()
    local -r ccache="$(which ccache 2>/dev/null)"
    [[ -s "${ccache}" ]] && make_command+=(ccache)
    make_command+=(make)
    run_clean "${make_command[@]}" || return
    mkdir -p "${pythonpath}" || return
    run_clean make PYTHONPATH="${pythonpath}" install || return
    cd "${NGHTTP2_BASE}" || return
    if [[ -e default ]] || {
        ln -sf "${version}" default
    }
}

install_nghttp2_main "$@"
